// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OnlineConcertTicketSales.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210617073042_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Concerts.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cea51056-4180-45e6-9007-b92b2c4e806a"),
                            ArtistName = "The Beatles",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("7ecf51f4-d7a1-4446-a394-9685445c548d"),
                            ArtistName = "The Rolling Stones",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("f32cba10-8b39-430b-904e-1013ce10bd7e"),
                            ArtistName = "Queen",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("772a66e2-1758-429a-bf2a-fa879c0a814b"),
                            ArtistName = "AC/DC",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("fba81401-9ecb-4b88-bc76-f94a8cf2febf"),
                            ArtistName = "Pink Floyd",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("d50c5b99-49f3-49ff-89f3-3e4c6903209e"),
                            ArtistName = "Led Zeppelin",
                            GenreId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870")
                        },
                        new
                        {
                            Id = new Guid("e8af3832-2e4f-489f-b282-94751285f4d4"),
                            ArtistName = "Miles Davis",
                            GenreId = new Guid("6d3dbb7d-6297-4839-aaa5-650760356875")
                        },
                        new
                        {
                            Id = new Guid("c1da350a-166a-490f-8430-d1fab16b24e7"),
                            ArtistName = "Louis Armstrong",
                            GenreId = new Guid("6d3dbb7d-6297-4839-aaa5-650760356875")
                        },
                        new
                        {
                            Id = new Guid("f545753e-b49f-45b9-91ee-de477d559365"),
                            ArtistName = "John Coltrane",
                            GenreId = new Guid("6d3dbb7d-6297-4839-aaa5-650760356875")
                        },
                        new
                        {
                            Id = new Guid("6a68cdd0-30c1-4b8c-9d3c-278c56bc7447"),
                            ArtistName = "Luke Combs",
                            GenreId = new Guid("4a4395c0-b3ce-4d32-916f-30200e9c7903")
                        },
                        new
                        {
                            Id = new Guid("1cf59f25-ea0f-46e1-9386-76d684e851ba"),
                            ArtistName = "Morgan Wallen",
                            GenreId = new Guid("4a4395c0-b3ce-4d32-916f-30200e9c7903")
                        },
                        new
                        {
                            Id = new Guid("bf0d8839-8205-4b38-ba5e-fe485409f423"),
                            ArtistName = "Kane Brown",
                            GenreId = new Guid("4a4395c0-b3ce-4d32-916f-30200e9c7903")
                        });
                });

            modelBuilder.Entity("Entities.Models.Concerts.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreName")
                        .HasColumnType("int")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            GenreName = 9
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            GenreName = 1
                        },
                        new
                        {
                            Id = new Guid("4a4395c0-b3ce-4d32-916f-30200e9c7903"),
                            GenreName = 0
                        },
                        new
                        {
                            Id = new Guid("2deefc3e-f1a9-4e70-9ebb-85fb2d3a9bef"),
                            GenreName = 2
                        },
                        new
                        {
                            Id = new Guid("6d3dbb7d-6297-4839-aaa5-650760356875"),
                            GenreName = 4
                        },
                        new
                        {
                            Id = new Guid("286d0569-5f6e-44c9-939f-aa0165353694"),
                            GenreName = 5
                        },
                        new
                        {
                            Id = new Guid("e04ba65d-1c39-4895-9c9a-a5ddee3e014a"),
                            GenreName = 11
                        });
                });

            modelBuilder.Entity("Entities.Models.Concerts.Artist", b =>
                {
                    b.HasOne("Entities.Models.Concerts.Genre", "Genre")
                        .WithMany("Artists")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
